### ISSUE TITLE
App scale is inconstant with Gnosis Safe UI

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/safe-module-manager#13]
The Module Manager elements are styled fairly consistently with the Gnosis Safe UI, however they are displayed much larger than similar elements in the Safe UI.

We should make the scale of the elements consistent with the Gnosis Sage UI.

![image](https://user-images.githubusercontent.com/8453294/130669815-c84eb621-365f-4a34-9248-828f381b4b49.png)

**Comment by samepant** [comment]
@auryn-macmillan  I went ahead and did the dev to adjust the designs a bit, let me know what you think and if there is anything i should change before opening a pr

![Screen Shot 2021-08-30 at 1 14 25 PM](https://user-images.githubusercontent.com/6718506/131378625-82402e8c-ac69-406e-81d4-1eabeb75b6ae.png)
![Screen Shot 2021-08-30 at 1 11 49 PM](https://user-images.githubusercontent.com/6718506/131378659-adbe1bf4-3a71-4d9a-bd28-cd5b55ab4212.png)
![Screen Shot 2021-08-30 at 1 11 56 PM](https://user-images.githubusercontent.com/6718506/131378674-c3734b2a-6e3e-4971-9d87-1a74e90eb22a.png)
![Screen Shot 2021-08-30 at 1 14 16 PM](https://user-images.githubusercontent.com/6718506/131378689-026d1e5a-6fa0-4b0c-b8a3-ea7841f29142.png)

**Comment by auryn-macmillan** [comment]
Yeah, I think that looks really nice!
