### ISSUE TITLE
Update to latest version of each of the modules.

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/safe-module-manager#16]
- [x] Delay
- [x] Reality (formerly dao-module)
- [x] AMB Module (formerly SafeBridge)
- [x] Exit (formerly SafeExit)

**Comment by carlosfebres** [comment]
@auryn-macmillan we are currently just using the Delay and Reality modules. So, I think there's not need to update the AMD and Exit module for now

**Comment by auryn-macmillan** [comment]
We should add the AMB and Exit modules :smile:

**Comment by carlosfebres** [comment]
I created a new issue to add these modules https://github.com/gnosis/safe-module-manager/issues/26
