### ISSUE TITLE
Switch module-factory out for zodaic

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/safe-module-manager#22]
module-factory repo is migrating to the zodiac repo, we need to switch out all of the imports.

**Comment by carlosfebres** [comment]
I updated the code to use the zodiac repo + the new contracts. (https://github.com/gnosis/safe-module-manager/pull/21/commits/c1fbab482e470d1c78bedbb72167cbc7b8b60cc9)
I had to do some changes to the Zodiac Repo to make able to be used as a library. (https://github.com/gnosis/zodiac/pull/12).
