### ISSUE TITLE
Add AMB & Exit Module 

### ISSUE THREAD

**Issue by carlosfebres** [gnosis/safe-module-manager#26]

**Comment by carlosfebres** [comment]
I've added the AMB & Exit modules in this commit https://github.com/gnosis/safe-module-manager/pull/21/commits/b0004dfad28121c4b3dbc425fd93c22c74d3d8b2

I created the following modals:

| EXIT | AMB |
| - | - |
| ![Screenshot from 2021-08-31 02-14-28](https://user-images.githubusercontent.com/2939980/131609102-84a50dd8-e0b1-49c3-8179-fed13c7b4923.png) | ![Screenshot from 2021-08-31 02-14-16](https://user-images.githubusercontent.com/2939980/131609104-7c79b9ea-afdc-435b-a361-d3e2f7351fea.png) |

**Comment by carlosfebres** [comment]
@samepant do you think the fields names/layout and module descriptions are fine?

**Comment by auryn-macmillan** [comment]
Yeah, they look good to me.

For the SafeExit module, we should give the user the option to deploy a circulating supply contract.

**Comment by carlosfebres** [comment]
@auryn-macmillan ok, few questions: 
1. should we deploy a proxy or the full contract?
2. should we only let the user deploy a new circulating supply contract or provide both options (deploy and enter an address)

**Comment by auryn-macmillan** [comment]
They should have both options.

If they deploy a new circulating supply contract, we should also allow them to set the circulating supply.

**Comment by carlosfebres** [comment]
> They should have both options.
> 
> If they deploy a new circulating supply contract, we should also allow them to set the circulating supply.

Added feature in PR https://github.com/gnosis/safe-module-manager/pull/27
