### ISSUE TITLE
Putting in too many digits into input crashes app

### ISSUE THREAD

**Issue by samepant** [gnosis/safe-module-manager#28]
If I input too many digits into the Cooldown input, the app crashes and I get this error:
![Screen Shot 2021-09-02 at 3 42 22 PM](https://user-images.githubusercontent.com/6718506/131906347-a125e436-e7a5-40da-a84a-856e676446d4.png)

Ideally, a simple error state on the field would show.

**Comment by carlosfebres** [comment]
Thanks for catching this! 
Fixed in this commit https://github.com/gnosis/safe-module-manager/pull/21/commits/61bbda31be4daa110abeec10054d53933e00d81d
