### ISSUE TITLE
Attach existing modules when no modules are installed

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/safe-module-manager#5]
![image](https://user-images.githubusercontent.com/8453294/126021752-4eb417fe-cc01-4ef8-ad5a-1d81647fe8cd.png)
![image](https://user-images.githubusercontent.com/8453294/126021758-9d9e21dc-f8f2-43fd-a6dd-6e5f055fc5e9.png)

The "attach existing modules" section shows up even when no modules are installed.

@samepant, I actually think we should scrap this feature, since the delay module and the DAO module have no setter function for the `executor` variable.

**Comment by samepant** [comment]
Ah, so when the DAO module is initially deployed it needs to have an existing delay module set as the executor?

**Comment by auryn-macmillan** [comment]
Correct.

**Comment by auryn-macmillan** [comment]
@carlosfebres if there are no delay-modules installed, let's just not display this. Since we don't have a flow for deploying and initializing the delay module before the other modules.
